src/slide_viewer/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('slides.urls', namespace='slides')),
    url(r'^users/', include('users.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.VIEWERJS_URL, document_root=settings.VIEWERJS_ROOT)

src/slides/urls.py
from django.conf.urls import url

from .views import display_slides, add_slides, user_slides, delete_slide


urlpatterns = [
    url(r'^$', display_slides, name='view'),
    url(r'^my-slides/$', user_slides, name='user_sld'),
    url(r'^add/$', add_slides, name='add'),
    url(r'^delete/(?P<pk>\d+)/$', delete_slide, name='delete'),
]

src/users/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import register 


urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^login/$', LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

src/slides/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save


from .utils import unique_slug_generator

User = settings.AUTH_USER_MODEL

class SlideUpload(models.Model):
	slide_id	= models.IntegerField(default=0)
	name		= models.CharField(max_length=120, null=True, blank=True)
	slide_url 	= models.FileField(null=True, blank=True)

	def __str__(self):
		return str(self.slide_url)

class Slide(models.Model):
	uploaded_by	= models.ForeignKey(User)
	title 		= models.CharField(max_length=120, null=True, blank=True)
	description = models.TextField(null=True, blank=True)
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)
	slug 		= models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.title


# using pre_save function to generate unique slug before saving it to db
def slide_pre_save_signal(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(slide_pre_save_signal, sender=Slide)

src/slides/forms.py
from django import forms
from django.core.validators import FileExtensionValidator


class AddSlide(forms.Form):
	title 		= forms.CharField()
	description = forms.CharField(required=False)
	slide 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)])
	slide2 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide3 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide4 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide5 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide6	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide7 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide8 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide9 	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)
	slide10	= forms.FileField(validators=[FileExtensionValidator(
												allowed_extensions=['odp', 'fodp']
												)], required=False)

src/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

src/slides/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from slide_viewer.settings import CDN_DOMAIN

from .models import Slide, SlideUpload
from .forms import AddSlide


@login_required()
def add_slides(request):
	form = AddSlide(request.POST or None, request.FILES or None)
	errors = None
	if form.is_valid():
		if request.user.is_authenticated():
			
			# saving the details in the db
			obj = Slide.objects.create(
					title = form.cleaned_data.get('title'), 
					description = form.cleaned_data.get('description'),
					uploaded_by = request.user
				)

			# uploading the first slide with same id
			query = Slide.objects.latest('id')
			obj = SlideUpload.objects.create(
					slide_id = query.id,
					name = form.cleaned_data.get('title'),
					slide_url = form.cleaned_data.get('slide'),
				)

			# looping through all other slides and uploading with same id
			for i in range(2,11):
				extra = 'slide' + str(i)
				if (str(form.cleaned_data.get(extra)) != 'None'):
					obj = SlideUpload.objects.create(
						slide_id = query.id,
						name = form.cleaned_data.get('title'), 
						slide_url = form.cleaned_data.get(extra),
					)
			return redirect('slides:view')
			
	if form.errors:
		errors = form.errors

	template_name = 'slides/add_slides.html'
	context = {"form":form, "errors":errors}
	return render(request, template_name, context)


def display_slides(request):
	template_name = 'slides/display_slides.html'
	
	# querying Slide table from db
	queryset1 = Slide.objects.all().order_by('-pk')
	
	# querying SlideUpload table from db
	queryset2 = SlideUpload.objects.all()

	# domain of CDN where the slides will be uploaded
	cdn = CDN_DOMAIN

	context = {"object_list": queryset1, "slide_list":queryset2, "cdn":cdn}
	return render(request, template_name, context)


@login_required()
def user_slides(request):
	template_name = 'slides/user_slides.html'
	
	# querying Slide table from db
	queryset1 = Slide.objects.filter(uploaded_by=request.user).order_by('-pk')
	
	# querying SlideUpload table from db
	queryset2 = SlideUpload.objects.all()

	# domain of CDN where the slides will be uploaded
	cdn = CDN_DOMAIN

	context = {"object_list": queryset1, "slide_list":queryset2, "cdn":cdn}
	return render(request, template_name, context)


@login_required()
def delete_slide(request, pk):
	# querying Slide table from db to get single row and deleting it
	instance1 = get_object_or_404(Slide, pk=pk).delete()
	instance2 = SlideUpload.objects.filter(slide_id=pk).delete()

	messages.success(request, "Successfully deleted the slides")
	return redirect('slides:user_sld')

src/users/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect


from .forms import UserRegisterForm


def register(request):
	form = UserRegisterForm(request.POST or None)
	errors = None
	if form.is_valid():
		form.save()
		messages.success(request, 'Account created successfully! Now login to continue.')
		return HttpResponseRedirect('/users/login/')
	
	if form.errors:
		errors = form.errors

	template_name = 'users/register.html'
	context = {"form":form, "errors":errors}
	return render(request, template_name, context)

src/slides/templates/slides/add_slides.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="content-section">
			<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Add Slides</legend>
					{% if errors %}
						<p>{{ errors }}</p><br>
					{% endif %}	
					<div>
						<div class="form-group">
                            <label for="name"> Title:</label>
                            <div><input type="text" name="title" size="65"></div>
                        </div>
                        <div class="form-group">
                            <label for="name"> Description:</label>
                            <div><textarea rows="4" cols="65" name="description"></textarea></div>
                        </div>
					    <div class="form-group add_form">
                            <label for="name"> Select Slides:</label>
                            <div><input type="file" name="slide"></div><br>
                        </div>
                        <button class="add_slide"><i class="fa fa-plus"></i> Add more</button><br>
				     </div>
				</fieldset>
				<div class="form-group">
					<center>
					<button class="btn btn-lg btn-info" type="submit">Upload</button>
					</center>
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock content %}


{% block JS %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
// JS script for adding multiple file upload fields in the form.
$(document).ready(function() {
	 var x = 2;
	   $('.add_slide').click(function(e){ 
	        e.preventDefault();
	 		if(x <= 10){
	        $('.add_form').append('<div class="row"><div><input type="file" id="extra" name="slide" class="col-md-10"></div><a href="#" class="remove_field"><i class="fa fa-times"></i></a><br><br></div>'); 
	        document.getElementById("extra").name = 'slide' + x;
	        document.getElementById("extra").id = 'sld';
	        x++;
		}
		else if (x == 11){
	 		$('.add_form').append('<p>You can only add 10 slides at a time</p>'); 
	        x++;
	    }
	});
	   
    $('.add_form').on("click",".remove_field", function(e){ 
		e.preventDefault(); 
		$(this).parent('div').remove();
		x--;		
    })
});
	
</script>

{% endblock JS %}

src/slides/templates/slides/display_slides.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

		
	<section id="portfolio">
		<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<div class="section-title">
					<h2>Top Slides and Presentations</h2>
				</div>
			</div>
		</div>
		<div class="row row-0-gutter">
			{% for obj in object_list %}
			<div class="row row-0-gutter">
						<div class="col-md-8 col-md-offset-2 col-0-gutter">
							<h2><strong>{{ obj.title }}</strong></h2>
							<p>{{ obj.description }}</p>
							{% for sld in slide_list %}
							{% if sld.slide_id == obj.id %}
								<a href="/viewerjs/index.html#{{ cdn }}/media/{{ sld.slide_url }}" target="_blank">
								<button class="btn btn-info" style="margin: 0 5px 10px 0;">View Slides</button>
								</a>
							{% endif %}
							{% endfor %}
							<hr>
						</div>
						</div>
			{% endfor %}
		</div>

		</div>
	</section>

	<section id="about" class="mz-module">
		<div class="container light-bg">
			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="section-title">
						<h2>ABOUT</h2>
					</div>
				</div>
				<div class="col-md-10 col-md-offset-1 text-center">
					<div class="mz-about-container">
						<p>Django Slide Viewer is a platform where users can register and then upload their slides. These slides can be viewed by anyone. Accepted Slide Formats are ODP, FODP <br>
						This project was made as a screening task for the <a href="https://fossee.in/" target="_blank">FOSSEE Fellowship 2019 Collaborative Communities</a></p><br>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock content %}

src/slides/templates/slides/user_slides.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}

		<section id="portfolio">
			<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="section-title">
						<h2>My Slides and Presentations</h2>
					</div>
				</div>
			</div>
			<div class="row row-0-gutter">
				{% for obj in object_list %}

				       
						<div class="row row-0-gutter">
						<div class="col-md-8 col-md-offset-2 col-0-gutter">
							<h2><strong>{{ obj.title }}</strong></h2>
							<p>{{ obj.description }}</p>
							{% for sld in slide_list %}
							{% if sld.slide_id == obj.id %}
							<a href="/viewerjs/index.html#{{ cdn }}/media/{{ sld.slide_url }}" target="_blank">
							<button class="btn btn-info" style="margin: 0 5px 10px 0;">View Slides</button>
							</a>
							{% endif %}
							{% endfor %}
							<br>
							{% if request.user.is_authenticated %}
							{% if obj.uploaded_by == request.user %}
							<a href="{% url 'slides:delete' pk=obj.pk %}">
								<button class="btn btn-danger">Delete Slides</button>
							</a>
							{% endif %}
							{% endif %}
							<hr>
						</div>
						</div>

				{% endfor %}
			</div>

			</div>
		</section>


{% endblock content %}

src/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="A simple Slide Viewer made with Python and Django.">
		<meta name="author" content="Nishant Ranjan">
		<link rel="icon" href="favicon.ico">
		<title>Django Slide Viewer</title>
		<!-- Bootstrap core CSS -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<!-- Custom styles for this template -->
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
	</head>
	<body id="page-top">
		<div class="allButFooter">
		<!-- Navigation -->
		<nav class="navbar navbar-default">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header page-scroll">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand page-scroll" href="{% url 'slides:view' %}"><h1><strong><em>Django Slide Viewer</em></strong></h1></a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						{% if user.is_authenticated %}
						<li>
							<a class="page-scroll" href="{% url 'slides:view' %}">Home</a>
						</li>
						<li>
							<a class="page-scroll" href="{% url 'slides:add' %}">Add Slides</a>
						</li>
						<li>
							<a class="page-scroll" href="{% url 'slides:user_sld' %}">My Slides</a>
						</li>
						<li>
							<a class="page-scroll" href="{% url 'logout' %}">Log Out</a>
						</li>	
						{% else %}
						<li>
							<a class="page-scroll" href="{% url 'register' %}">Register</a>
						</li>
						<li>
							<a class="page-scroll" href="{% url 'login' %}">Login</a>
						</li>
						{% endif %}
					</ul>
				</div>
		</nav>
		<br>


			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			{% block content %}

			{% endblock content %}
</div>

		<p id="back-top">
			<a href="#top"><i class="fa fa-angle-up"></i></a>
		</p>
		<footer>
			<div class="container text-center">
				<p>Designed by <a href="https://meetnishant.com"><span>Nishant Ranjan</span></a></p>
			</div>
		</footer>
		


		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/SmoothScroll.js' %}"></script>
		<script src="{% static 'js/theme-scripts.js' %}"></script>
		{% block JS %}

		{% endblock JS %}

	</body>
</html>

src/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="content-section">
			<form method="POST"> {% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Log In</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Login</button>
				</div>
			</form>
			<div class="border-top pt-3">
				<p class="text-muted">
					Need an account? <a href="{% url 'register' %}" class="ml-2">Sign Up Now!</a>
				</p>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

src/users/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h2>You have been logged out successfully</h2>
		<div class="border-top pt-3">
			<p class="text-muted">
				<a href="{% url 'login' %}">Login again?</a>
			</p>
		</div>
	</div>
</div>		


{% endblock content %}

src/users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="content-section">
			<form method="POST"> {% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Register Now</legend>
					{% if errors %}
					{{ errors }}
					{% endif %}
					<br>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Sign Up!</button>
				</div>
			</form>
			<div class="border-top pt-3">
				<p class="text-muted">
					Already have an account? <a href="{% url 'login' %}" class="ml-2">Sign In</a>
				</p>
			</div>
		</div>
	</div>
</div>

{% endblock content %}